using UnityEngine;
using VRG.ChapterFramework;

// Auto-generated by Chapter Framework

namespace VRG.ChapterFramework.Editor.Templates
{
    public class Quiz : Chapter
    {
        // Start is called once before the first execution of Update after the MonoBehaviour is created
        void Start()
        {

        }

        // Update is called once per frame
        void Update()
        {

        }
    }
}
